### ISSUE TITLE
Protocol to integrate:  BEEFY

### ISSUE THREAD

**Issue by tcheee** [Valha-xyz/valha-defi-connectors#20]
Hey, 

 We would like to integrate BEEFY but we haven't had the time to do so yet. Would be awesome if someone try to create a connector for this protocol. 

 Here is the documentation we found:
- Protocol documentation: https://docs.beefy.finance/ 
 - Contracts list: https://immunefi.com/bounty/beefyfinance/ 

 If you have any question about it, please ask anything in the Discord!

**Comment by Kayanski** [comment]
Integration is in PR #55 , the longest part is querying the protocol pools. This should be easier for protocols to integrate themselves.
