### ISSUE TITLE
Protocol to integrate: UBESWAP

### ISSUE THREAD

**Issue by tcheee** [Valha-xyz/valha-defi-connectors#46]
Hey,

We would like to integrate UBESWAP but we haven't had the time to do so yet. Would be awesome if someone try to create a connector for this protocol.

Here is the documentation we found:

Protocol documentation: https://docs.ubeswap.org/
Contracts list: N/A
If you have any question about it, please ask anything in the Discord!

**Comment by bertux** [comment]
I start the integration with contracts list at https://docs.ubeswap.org/code-and-contracts/contract-addresses
